name: Missing Localization Keys

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "Data/localization/**"
  workflow_dispatch:

jobs:
  test-loc-keys:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run localization consistency check
        run: python Data/localization/get_missing_loc_keys.py
